#!/bin/sh


PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#

mount -a
#mkdir -p /dev/pts
#mount -t devpts devpts /dev/pts
#mount -n -t usbfs none /proc/bus/usb
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
#mkdir -p /var/lock

#modprobe s5pv210_wm8960
#modprobe ds18b20
#modprobe rt5370sta

#hwclock -s
#EmbedSky_wdg &

#ifconfig eth0 192.168.0.131
#ifconfig lo 127.0.0.1
#net_set &

#/etc/rc.d/init.d/netd start
#/etc/rc.d/init.d/httpd start

#pda &
#/bin/hostname -F /etc/sysconfig/HOSTNAME

#insmod mt7601Usta.ko
#insmod rt5370sta.ko
#insmod ft5x06_ts.ko
#ifconfig wlan0 up
#ifconfig wlan0 192.168.0.200  
#route add default gw 192.168.0.1 netmask 255.255.255.0
#wpa_supplicant -B -iwlan0 -c /etc/wpa_supplicant.conf
